version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for ruby
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
